### ISSUE TITLE
Actions are run twice for internally opened pull request

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-client-gateway#568]
## Issue

In order to enable external contributions we had to add `on: pull_request` to our workflow. This will trigger a run of a PR opened from a fork, but in the case of an internal branch of the project the event `push` and `pull_request` trigger the workflow twice. 

We need to trigger our workflow only when: 
- push to main
- pushes to PR
- Create a PR (external contributions from forks)
- Tags 

Usage of composite actions could prove useful: https://docs.github.com/en/actions/creating-actions/creating-a-composite-run-steps-action

## Solution 1

Partition our jobs and have a workflow per row as shown in the image below:

![image](https://user-images.githubusercontent.com/11056031/129553853-4f960f42-b9a9-4c11-af1b-26d2726a6446.png)

## Solution 2

Find the combination of trigger events that allows us to run our current workflow in the scenarios listed in the top section of the issue. Something along the lines of:

```yml
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Also trigger on page_build, as well as release created events
  page_build:
  release:
    types: # This configuration does not affect the page_build event above
      - created
```

For more information: https://docs.github.com/en/actions/reference/events-that-trigger-workflows
